import Models from "../classes/classModel";
import sch from "../schemas/recommendations";
import History from "../schemas/history";
import WellnessDetail from "../schemas/wellness_details";
import { getGeminiAI } from "../helpers/masterFunction"

class recommendationsModel extends Models{
    constructor(){
        super(sch)
        this.sorting = { created_at: -1 }
    }

    async getAll(query={}){
        // console.log({udata: this.udata, query})
        const datas = []
        const resp = await this.model.findOne({...query, user_id: this.udata._id}).sort(this.sorting)
        if(!resp) throw new NotFoundError('Data Not Found.')
        // for (let i = 0; i < resp.length; i++) {
        //     const e = resp[i];
            
        //     const obj = { ...e._doc, meals: meals }
        //     datas.push(obj)
            
        // }
        const detail  = await WellnessDetail.findOne({ user_id: resp.user_id })
        var meals = []
        if (detail.bmi_category == 'Normal') {
            meals = [{"hari": "Senin", "makanan": [{"jenis": "Sarapan", "keterangan": "Nasi putih, telur dadar, sayur bayam"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, ayam goreng, sayur sop"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, ikan bakar, sayur kangkung"}]}, {"hari": "Selasa", "makanan": [{"jenis": "Sarapan", "keterangan": "Bubur ayam"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, rendang, sayur nangka"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, tahu tempe bacem, sayur buncis"}]}, {"hari": "Rabu", "makanan": [{"jenis": "Sarapan", "keterangan": "Roti gandum, selai kacang, susu"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, semur jengkol, sayur sawi"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, pepes ikan, sayur oyong"}]}, {"hari": "Kamis", "makanan": [{"jenis": "Sarapan", "keterangan": "Mie ayam"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, gulai kambing, sayur labu siam"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, sate ayam, sayur toge"}]}, {"hari": "Jumat", "makanan": [{"jenis": "Sarapan", "keterangan": "Nasi uduk, telur balado"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, opor ayam, sayur lodeh"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, tumis kangkung, tahu goreng"}]}, {"hari": "Sabtu", "makanan": [{"jenis": "Sarapan", "keterangan": "Lontong sayur"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, ayam bakar, sayur asem"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, ikan goreng, sayur bening"}]}, {"hari": "Minggu", "makanan": [{"jenis": "Sarapan", "keterangan": "Nasi kuning, ayam suwir"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, rendang, sayur pare"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, sup ayam, sayur bayam"}]}]
        } else if (detail.bmi_category == 'Kurang Berat Badan') {
            meals = [{"hari": "Senin", "makanan": [{"jenis": "Sarapan", "keterangan": "Nasi putih 1/2 piring, telur rebus 1 butir, tempe goreng 1 potong, jus buah (jeruk/apel)"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih 1 piring, ayam bakar 1 potong, sayur tumis, tahu goreng 1 potong, es buah"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih 1/2 piring, ikan bakar 1 potong, sayur bening, tahu bacem, buah pisang"}]}, {"hari": "Selasa", "makanan": [{"jenis": "Sarapan", "keterangan": "Bubur ayam dengan suwiran ayam dan daun bawang"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih 1 piring, rendang daging sapi 1 potong, sayur sop, sambel terasi, es teh"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih 1/2 piring, ikan goreng 1 potong, sayur asem, tempe orek, buah melon"}]}, {"hari": "Rabu", "makanan": [{"jenis": "Sarapan", "keterangan": "Roti gandum isi pisang dan selai kacang"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih 1 piring, semur jengkol 1 potong, sayur lodeh, tahu bacem, es jeruk"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih 1/2 piring, ayam goreng 1 potong, sayur capcay, tahu telur, buah anggur"}]}, {"hari": "Kamis", "makanan": [{"jenis": "Sarapan", "keterangan": "Oatmeal dengan susu rendah lemak, buah berry"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih 1 piring, gulai ikan kakap 1 potong, sayur tumis kangkung, sambel ijo, es teh manis"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih 1/2 piring, cumi bakar 1 potong, sayur sop, tahu goreng, buah mangga"}]}, {"hari": "Jumat", "makanan": [{"jenis": "Sarapan", "keterangan": "Nasi putih 1/2 piring, telur dadar 1 butir, tumis sayuran"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih 1 piring, sate ayam 5 tusuk, sayur urap, sambel kecap, es jeruk nipis"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih 1/2 piring, ikan pepes, sayur asem, tahu tempe, buah jambu"}]}, {"hari": "Sabtu", "makanan": [{"jenis": "Sarapan", "keterangan": "Nasi putih 1/2 piring, nasi uduk, telur ceplok"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih 1 piring, tongseng daging sapi 1 potong, sayur buncis, sambel terasi, es teh manis"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih 1/2 piring, ikan bakar 1 potong, sayur bening, tahu bacem, buah semangka"}]}, {"hari": "Minggu", "makanan": [{"jenis": "Sarapan", "keterangan": "Roti tawar gandum, selai kacang, susu rendah lemak"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih 1 piring, ayam goreng 1 potong, sayur tumis, tahu goreng, es teh manis"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih 1/2 piring, ikan goreng 1 potong, sayur sop, tempe orek, buah pisang"}]}]
        } else if (detail.bmi_category == 'Kelebihan Berat Badan') {
            meals = [{"hari": "Senin", "makanan": [{"jenis": "Sarapan", "keterangan": "Bubur ayam dengan sedikit minyak dan nasi putih"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, ikan bakar, sayur bening, buah semangka"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, ayam rebus, tumis sayuran, buah pisang"}]}, {"hari": "Selasa", "makanan": [{"jenis": "Sarapan", "keterangan": "Oatmeal dengan susu rendah lemak dan buah beri"}, {"jenis": "Makan Siang", "keterangan": "Nasi merah, tahu bacem, sayur sop, buah melon"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, tempe goreng, sayur asem, buah jeruk"}]}, {"hari": "Rabu", "makanan": [{"jenis": "Sarapan", "keterangan": "Roti gandum dengan selai kacang"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, ikan goreng, sayur lodeh, buah apel"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, dada ayam panggang, tumis kangkung, buah pepaya"}]}, {"hari": "Kamis", "makanan": [{"jenis": "Sarapan", "keterangan": "Telur rebus dengan roti gandum"}, {"jenis": "Makan Siang", "keterangan": "Nasi merah, tahu gembus, sayur capcay, buah pir"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, ikan kukus, sayur bening, buah mangga"}]}, {"hari": "Jumat", "makanan": [{"jenis": "Sarapan", "keterangan": "Yogurt rendah lemak dengan granola"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, ayam goreng, sayur tumis, buah semangka"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, tahu telur, sayur asem, buah pisang"}]}, {"hari": "Sabtu", "makanan": [{"jenis": "Sarapan", "keterangan": "Sereal dengan susu rendah lemak"}, {"jenis": "Makan Siang", "keterangan": "Nasi merah, ikan bakar, sayur sop, buah melon"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, tempe orek, sayur lodeh, buah jeruk"}]}, {"hari": "Minggu", "makanan": [{"jenis": "Sarapan", "keterangan": "Roti gandum dengan selai kacang"}, {"jenis": "Makan Siang", "keterangan": "Nasi putih, ayam rebus, sayur bening, buah apel"}, {"jenis": "Makan Malam", "keterangan": "Nasi putih, ikan kukus, sayur tumis, buah pepaya"}]}]
        } else if (detail.bmi_category == 'Obesitas') {
            meals = [{"hari": "Senin", "makanan": [{"jenis": "Sarapan", "keterangan": "Oatmeal dengan susu rendah lemak, buah beri, dan kacang-kacangan"}, {"jenis": "Makan Siang", "keterangan": "Ikan bakar dengan nasi merah dan sayur tumis"}, {"jenis": "Makan Malam", "keterangan": "Sup ayam dengan sayur dan tahu"}]}, {"hari": "Selasa", "makanan": [{"jenis": "Sarapan", "keterangan": "Telur rebus dengan roti gandum"}, {"jenis": "Makan Siang", "keterangan": "Salad ayam dengan dressing rendah lemak"}, {"jenis": "Makan Malam", "keterangan": "Nasi merah dengan tumis sayuran dan tempe"}]}, {"hari": "Rabu", "makanan": [{"jenis": "Sarapan", "keterangan": "Yogurt rendah lemak dengan granola dan buah"}, {"jenis": "Makan Siang", "keterangan": "Ayam rebus dengan nasi merah dan sayur"}, {"jenis": "Makan Malam", "keterangan": "Lontong sayur dengan tahu dan tempe"}]}, {"hari": "Kamis", "makanan": [{"jenis": "Sarapan", "keterangan": "Bubur kacang hijau dengan susu rendah lemak"}, {"jenis": "Makan Siang", "keterangan": "Nasi merah dengan tumis ikan dan sayuran"}, {"jenis": "Makan Malam", "keterangan": "Soto ayam dengan nasi merah"}]}, {"hari": "Jumat", "makanan": [{"jenis": "Sarapan", "keterangan": "Roti gandum dengan selai kacang"}, {"jenis": "Makan Siang", "keterangan": "Tahu isi dengan nasi merah dan sayur"}, {"jenis": "Makan Malam", "keterangan": "Mie ayam dengan sayur"}]}, {"hari": "Sabtu", "makanan": [{"jenis": "Sarapan", "keterangan": "Pancake gandum dengan buah"}, {"jenis": "Makan Siang", "keterangan": "Nasi merah dengan tumis daging sapi dan sayuran"}, {"jenis": "Makan Malam", "keterangan": "Pepes ikan dengan nasi merah"}]}, {"hari": "Minggu", "makanan": [{"jenis": "Sarapan", "keterangan": "Telur orak-arik dengan sayuran"}, {"jenis": "Makan Siang", "keterangan": "Nasi merah dengan tumis udang dan sayuran"}, {"jenis": "Makan Malam", "keterangan": "Sate ayam dengan nasi merah"}]}]
        }
        console.log({meals})
        return { msg: 'Data retrieved.', data: {...resp._doc, meals: meals}}
    }

}

module.exports=recommendationsModel